=========================================================================================================================================================================
																		APEX TDC INNOVATION
=========================================================================================================================================================================																					
URL Download dados: https://coronavirus.saude.mg.gov.br/painel
Apex URL: https://apex.oracle.com/pls/apex/
=========================================================================================================================================================================

=========================================================================================================================================================================
=========================================================================== CRIAÇÃO DE TABLEAS ========================================================================== 
=========================================================================================================================================================================

=========================================================================================================================================================================
													TABELA LISTA_URS (Unidades Regional de Saúde)
=========================================================================================================================================================================
CREATE table "URS" (
    "ID"         NUMBER,
    "URS_NAME"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_URS" primary key ("ID")
)
/

CREATE sequence "SEQ_URS" 
/

CREATE trigger "TRG_URS"  
  before insert on "URS"              
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_URS".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO URS (ID, URS_NAME) VALUES ('','ALFENAS')
	INTO URS (ID, URS_NAME) VALUES ('','BARBACENA')
	INTO URS (ID, URS_NAME) VALUES ('','BELO HORIZONTE')
	INTO URS (ID, URS_NAME) VALUES ('','CORONEL FABRICIANO')
	INTO URS (ID, URS_NAME) VALUES ('','DIAMANTINA')
	INTO URS (ID, URS_NAME) VALUES ('','DIVINOPOLIS')
	INTO URS (ID, URS_NAME) VALUES ('','GOVERNADOR VALADARES')
	INTO URS (ID, URS_NAME) VALUES ('','ITABIRA')
	INTO URS (ID, URS_NAME) VALUES ('','ITUIUTABA')
	INTO URS (ID, URS_NAME) VALUES ('','JANUARIA')
	INTO URS (ID, URS_NAME) VALUES ('','JUIZ DE FORA')
	INTO URS (ID, URS_NAME) VALUES ('','LEOPOLDINA')
	INTO URS (ID, URS_NAME) VALUES ('','MANHUACU')
	INTO URS (ID, URS_NAME) VALUES ('','MONTES CLAROS')
	INTO URS (ID, URS_NAME) VALUES ('','PASSOS')
	INTO URS (ID, URS_NAME) VALUES ('','PATOS DE MINAS')
	INTO URS (ID, URS_NAME) VALUES ('','PEDRA AZUL')
	INTO URS (ID, URS_NAME) VALUES ('','PIRAPORA')
	INTO URS (ID, URS_NAME) VALUES ('','PONTE NOVA')
	INTO URS (ID, URS_NAME) VALUES ('','POUSO ALEGRE')
	INTO URS (ID, URS_NAME) VALUES ('','SAO JOAO DEL REI')
	INTO URS (ID, URS_NAME) VALUES ('','SETE LAGOAS')
	INTO URS (ID, URS_NAME) VALUES ('','TEOFILO OTONI')
	INTO URS (ID, URS_NAME) VALUES ('','UBA')
	INTO URS (ID, URS_NAME) VALUES ('','UBERABA')
	INTO URS (ID, URS_NAME) VALUES ('','UBERLANDIA')
	INTO URS (ID, URS_NAME) VALUES ('','UNAI')
	INTO URS (ID, URS_NAME) VALUES ('','VARGINHA')
SELECT 1 FROM DUAL;
=========================================================================================================================================================================
														
=========================================================================================================================================================================
														TABELA LISTA_MICRO_REGIOES
=========================================================================================================================================================================
CREATE table "MICRO_REGIOES" (
    "ID"         NUMBER,
    "MICRO_REGIOES_NAME"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_MICRO_REGIOES" primary key ("ID")
)
/

CREATE sequence "SEQ_MICRO_REGIOES" 
/

CREATE trigger "TRG_MICRO_REGIOES"  
  before insert on "MICRO_REGIOES"              
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_MICRO_REGIOES".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','AGUAS FORMOSAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ALEM PARAIBA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ALFENAS MACHADO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ALMENARA JACINTO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ARACUAI')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ARAXA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','BARBACENA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','BELO HORIZONTE NOVA LIMA CAETE')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','BELO HORIZONTE NOVA LIMA CAETE')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','BETIM')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','BOCAIUVA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','BOM DESPACHO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','BRASILIA DE MINAS S  FRANCISCO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','CAMPO BELO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','CARANGOLA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','CARATINGA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','CASSIA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','CONGONHAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','CONSELHEIRO LAFAIETE')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','CONTAGEM')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','CORACAO DE JESUS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','CORONEL FABRICIANO TIMOTEO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','CURVELO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','DIAMANTINA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','DIVINOPOLIS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','FORMIGA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','FRANCISCO SA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','FRUTAL ITURAMA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','GOVERNADOR VALADARES')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','GUANHAES')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','GUAXUPE')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','IPATINGA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ITABIRA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ITAJUBA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ITAMBACURI')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ITAOBIM')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ITAUNA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','ITUIUTABA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','JANAUBA MONTE AZUL')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','JANUARIA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','JOAO MONLEVADE')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','JOAO PINHEIRO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','JUIZ DE FORA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','LAGOA DA PRATA STO ANT  MONTE')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','LAVRAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','LEOPOLDINA CATAGUASES')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','LIMA DUARTE')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','MANGA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','MANHUACU')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','MANTENA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','MONTES CLAROS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','MURIAE')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','NANUQUE')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','OLIVEIRA STO ANT  AMPARO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','OURO PRETO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','PADRE PARAISO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','PARA DE MINAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','PASSOS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','PATOS DE MINAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','PATROCINIO MONTE CARMELO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','PECANHA SAO JOAO EVANGELISTA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','PEDRA AZUL')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','PIRAPORA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','PIUMHI')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','POCOS DE CALDAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','PONTE NOVA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','POUSO ALEGRE')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','RESPLENDOR')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','SALINAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','SANTA MARIA DO SUACUI')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','SANTOS DUMONT')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','SAO GOTARDO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','SAO JOAO DEL REI')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','SAO JOAO NEPOMUCENO BICAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','SAO LOURENCO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','SAO SEBASTIAO DO PARAISO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','SERRO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','SETE LAGOAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','TAIOBEIRAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','TEOFILO OTONI MALACACHETA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','TRES CORACOES')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','TRES PONTAS')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','TURMALINA M  NOVAS CAPELINHA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','UBA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','UBERABA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','UBERLANDIA ARAGUARI')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','UNAI')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','VARGINHA')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','VESPASIANO')
	INTO MICRO_REGIOES (ID, MICRO_REGIOES_NAME) VALUES ('','VICOSA')
SELECT 1 FROM DUAL;
=========================================================================================================================================================================

=========================================================================================================================================================================
														TABELA LISTA_MACRO_REGIOES
=========================================================================================================================================================================
CREATE table "MACRO_REGIOES" (
    "ID"         NUMBER,
    "MACRO_REGIOES_NAME"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_MACRO_REGIOES" primary key ("ID")
)
/

CREATE sequence "SEQ_MACRO_REGIOES" 
/

CREATE trigger "TRG_MACRO_REGIOES"  
  before insert on "MACRO_REGIOES"              
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_MACRO_REGIOES".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','CENTRO')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','CENTRO SUL')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','JEQUITINHONHA')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','LESTE')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','LESTE DO SUL')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','NORDESTE')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','NOROESTE')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','NORTE')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','OESTE')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','SUDESTE')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','SUL')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','TRIANGULO DO NORTE')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','TRIANGULO DO SUL')
	INTO MACRO_REGIOES (ID, MACRO_REGIOES_NAME) VALUES ('','VALE DO ACO')
SELECT 1 FROM DUAL;
=========================================================================================================================================================================

=========================================================================================================================================================================
														TABELA LISTA_CLASSIFICAÇÃO_DOS_CASOS
=========================================================================================================================================================================
CREATE table "CLASSIFICACAO_CASOS" (
    "ID"         NUMBER,
    "CLASSIFICACAO"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_CLASSIFICACAO" primary key ("ID")
)
/

CREATE sequence "SEQ_CLASSIFICACAO" 
/

CREATE trigger "TRG_CLASSIFICACAO_CASOS"  
  before insert on "CLASSIFICACAO_CASOS"              
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_CLASSIFICACAO".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO CLASSIFICACAO_CASOS (ID, CLASSIFICACAO) VALUES ('','CONFIRMADO')
	INTO CLASSIFICACAO_CASOS (ID, CLASSIFICACAO) VALUES ('','NÃO CONFIRMADO')
SELECT 1 FROM DUAL;
=========================================================================================================================================================================

=========================================================================================================================================================================
														TABELA LISTA_SEXO
=========================================================================================================================================================================
CREATE table "SEXO" (
    "ID"         NUMBER,
    "SEXO"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_SEXO" primary key ("ID")
)
/

CREATE sequence "SEQ_SEXO" 
/

CREATE trigger "TRG_SEXO"  
  before insert on "SEXO"              
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_SEXO".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO SEXO (ID, SEXO) VALUES ('','FEMININO')
	INTO SEXO (ID, SEXO) VALUES ('','MASCULINO')
SELECT 1 FROM DUAL;
=========================================================================================================================================================================

=========================================================================================================================================================================
														TABELA LISTA_FAIXA_ETARIA
=========================================================================================================================================================================
CREATE table "FAIXA_ETARIA" (
    "ID"         NUMBER,
    "FAIXA_ETARIA"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_FAIXA_ETARIA" primary key ("ID")
)
/

CREATE sequence "SEQ_FAIXA_ETARIA" 
/

CREATE trigger "TRG_FAIXA_ETARIA"  
  before insert on "FAIXA_ETARIA"
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_FAIXA_ETARIA".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','0 A 9 ANOS')
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','10 A 19 ANOS')
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','20 A 29 ANOS')
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','30 A 39 ANOS')	
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','40 A 49 ANOS')	
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','50 A 59 ANOS')
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','60 A 69 ANOS')
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','70 A 79 ANOS')
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','80 A 89 ANOS')
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','90 A 99 ANOS')
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','100 A 109 ANOS')
	INTO FAIXA_ETARIA (ID, FAIXA_ETARIA) VALUES ('','110 A 119 ANOS')							
SELECT 1 FROM DUAL;
=========================================================================================================================================================================
																	TABELA LISTA_RACA
=========================================================================================================================================================================
CREATE table "RACA" (
    "ID"         NUMBER,
    "TIPO_RACA"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_RACA" primary key ("ID")
)
/

CREATE sequence "SEQ_RACA" 
/

CREATE trigger "TRG_RACA"  
  before insert on "RACA"
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_RACA".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO RACA (ID, TIPO_RACA) VALUES ('','AMARELA')
	INTO RACA (ID, TIPO_RACA) VALUES ('','BRANCA')
	INTO RACA (ID, TIPO_RACA) VALUES ('','INDIGENA')	
	INTO RACA (ID, TIPO_RACA) VALUES ('','PARDA')	
	INTO RACA (ID, TIPO_RACA) VALUES ('','PRETA')
	INTO RACA (ID, TIPO_RACA) VALUES ('','NÃO INFORMADO')							
SELECT 1 FROM DUAL;
=========================================================================================================================================================================

=========================================================================================================================================================================
																TABELA LISTA_COMORBIDADE
=========================================================================================================================================================================
CREATE table "COMORBIDADE" (
    "ID"         NUMBER,
    "TIPO_COMORBIDADE"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_COMORBIDADE" primary key ("ID")
)
/

CREATE sequence "SEQ_COMORBIDADE" 
/

CREATE trigger "TRG_COMORBIDADE"  
  before insert on "COMORBIDADE"
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_COMORBIDADE".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO COMORBIDADE (ID, TIPO_COMORBIDADE) VALUES ('','SIM')
	INTO COMORBIDADE (ID, TIPO_COMORBIDADE) VALUES ('','NÃO')
	INTO COMORBIDADE (ID, TIPO_COMORBIDADE) VALUES ('','NÃO INFORMADO')							
SELECT 1 FROM DUAL;
=========================================================================================================================================================================

=========================================================================================================================================================================
																	TABELA LISTA_ORIGEM_CASOS
=========================================================================================================================================================================
CREATE table "ORIGEM_CASOS" (
    "ID"         NUMBER,
    "ORIGEM"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_ORIGEM_CASOS" primary key ("ID")
)
/

CREATE sequence "SEQ_ORIGEM_CASOS" 
/

CREATE trigger "TGR_ORIGEM_CASOS"  
  before insert on "ORIGEM_CASOS"
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_ORIGEM_CASOS".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO ORIGEM_CASOS (ID, ORIGEM) VALUES ('','LABORATORIOS PUBLICOS E PRIVADOS')
	INTO ORIGEM_CASOS (ID, ORIGEM) VALUES ('','NÃO INFORMADO')
SELECT 1 FROM DUAL;
=========================================================================================================================================================================

=========================================================================================================================================================================
																TABELA LISTA_EVOLUCAO
=========================================================================================================================================================================
CREATE table "EVOLUCAO_CASOS" (
    "ID"         NUMBER,
    "TIPO"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_EVOLUCAO_CASOS" primary key ("ID")
)
/

CREATE sequence "SEQ_EVOLUCAO_CASOS" 
/

CREATE trigger "TGR_EVOLUCAO_CASOS"  
  before insert on "EVOLUCAO_CASOS"
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_EVOLUCAO_CASOS".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO EVOLUCAO_CASOS (ID, TIPO) VALUES ('','EM ACOMPANHAMENTO')
	INTO EVOLUCAO_CASOS (ID, TIPO) VALUES ('','ÓBITO')
	INTO EVOLUCAO_CASOS (ID, TIPO) VALUES ('','RECUPERADO')
	INTO EVOLUCAO_CASOS (ID, TIPO) VALUES ('','NÃO INFORMADO')
SELECT 1 FROM DUAL;
=========================================================================================================================================================================

=========================================================================================================================================================================
																TABELA LISTA_INTERNACAO
=========================================================================================================================================================================
CREATE table "INTERNACAO" (
    "ID"         NUMBER,
    "TIPO"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_INTERNACAO" primary key ("ID")
)
/

CREATE sequence "SEQ_INTERNACAO" 
/

CREATE trigger "TGR_INTERNACAO"  
  before insert on "INTERNACAO"
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_INTERNACAO".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  

INSERT ALL
	INTO INTERNACAO (ID, TIPO) VALUES ('','ENFERMARIA')
	INTO INTERNACAO (ID, TIPO) VALUES ('','UTI')
	INTO INTERNACAO (ID, TIPO) VALUES ('','NÃO INFORMADA')
SELECT 1 FROM DUAL;
=========================================================================================================================================================================

=========================================================================================================================================================================
															TABELA LISTA_MUNICIPIOS
=========================================================================================================================================================================
CREATE table "MUNICIPIOS" (
    "ID"         NUMBER,
    "NOME_MUNICIPIO"   VARCHAR2(200) NOT NULL,
    constraint  "CONST_NOME_MUNICIPIO" primary key ("ID")
)
/

CREATE sequence "SEQ_NOME_MUNICIPIO" 
/

CREATE trigger "TGR_NOME_MUNICIPIO"  
  before insert on "MUNICIPIOS"
  for each row 
begin  
  if :NEW."ID" is null then
    select "SEQ_NOME_MUNICIPIO".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/  
INSERT ALL
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ABADIA DOS DOURADOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ABAETÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ABRE CAMPO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ACAIACA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AGUA BOA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AGUA COMPRIDA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AGUANIL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AGUAS FORMOSAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AGUAS VERMELHAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AIMORÉS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AIURUOCA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALAGOA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALBERTINA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALFENAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALFREDO VASCONCELOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALMENARA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALPERCATA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALPINÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALTEROSA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALTO CAPARAÓ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALTO JEQUITIBÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALTO RIO DOCE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALVARENGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALVINÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALVORADA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ALÉM PARAÍBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AMPARO DO SERRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ANDRADAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ANDRELÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ANGELÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ANTÔNIO CARLOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ANTÔNIO DIAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ANTÔNIO PRADO DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARACITABA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARAGUARI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARANTINA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARAPONGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARAPORÃ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARAPUÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARAXÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARAÇAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARAÇUAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARAÚJOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARCEBURGO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARCOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AREADO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARGIRITA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARICANDUVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ARINOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ASTOLFO DUTRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ATALÉIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AUGUSTO DE LIMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','AÇUCENA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BAEPENDI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BALDIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BAMBUÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BANDEIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BANDEIRA DO SUL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BARBACENA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BARRA LONGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BARROSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BARÃO DE COCAIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BARÃO DE MONTE ALTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BELA VISTA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BELMIRO BRAGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BELO HORIZONTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BELO ORIENTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BELO VALE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BERILO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BERIZAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BERTÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BETIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BIAS FORTES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BICAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BIQUINHAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOA ESPERANÇA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOCAINA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOCAIÚVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOM DESPACHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOM JARDIM DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOM JESUS DA PENHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOM JESUS DO AMPARO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOM JESUS DO GALHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOM REPOUSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOM SUCESSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BONFIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BONFINÓPOLIS DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BONITO DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BORDA DA MATA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOTELHOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BOTUMIRIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BRASILÂNDIA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BRASÍLIA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BRASÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BRAÚNAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BRUMADINHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BRÁS PIRES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BUENO BRANDÃO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BUENÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BUGRE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BURITIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','BURITIZEIRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CABECEIRA GRANDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CABO VERDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CACHOEIRA DA PRATA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CACHOEIRA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CACHOEIRA DE PAJEÚ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CACHOEIRA DOURADA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAETANÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAETÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAIANA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAJURI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CALDAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMACHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMANDUCAIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMBUQUIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMBUÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMPANHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMPANÁRIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMPESTRE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMPINA VERDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMPO AZUL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMPO BELO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMPO DO MEIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMPO FLORIDO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMPOS ALTOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAMPOS GERAIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CANA VERDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CANAÃ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CANDEIAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CANTAGALO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CANÁPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAPARAÓ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAPELA NOVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAPELINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAPETINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAPIM BRANCO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAPINÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAPITÃO ANDRADE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAPITÃO ENÉAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAPITÓLIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAPUTIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARANAÍBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARANDAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARANGOLA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARATINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARBONITA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAREAÇU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARLOS CHAGAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARMO DA CACHOEIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARMO DA MATA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARMO DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARMO DO CAJURU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARMO DO PARANAÍBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARMO DO RIO CLARO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARMÉSIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARMÓPOLIS DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARNEIRINHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARRANCAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARVALHOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CARVALHÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CASA GRANDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CASCALHO RICO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CATAGUASES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CATAS ALTAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CATAS ALTAS DA NORUEGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CATUJI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CATUTI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CAXAMBU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CEDRO DO ABAETÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CENTRAL DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CENTRALINA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CHALÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CHAPADA DO NORTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CHAPADA GAÚCHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CHIADOR')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CHÁCARA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CIPOTÂNEA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CLARAVAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CLARO DOS POÇÕES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CLÁUDIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','COIMBRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','COLUNA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','COMENDADOR GOMES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','COMERCINHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONCEIÇÃO DA APARECIDA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONCEIÇÃO DA BARRA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONCEIÇÃO DAS ALAGOAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONCEIÇÃO DAS PEDRAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONCEIÇÃO DE IPANEMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONCEIÇÃO DO MATO DENTRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONCEIÇÃO DO PARÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONCEIÇÃO DO RIO VERDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONCEIÇÃO DOS OUROS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONFINS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONGONHAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONGONHAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONGONHAS DO NORTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONQUISTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONSELHEIRO LAFAIETE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONSELHEIRO PENA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONSOLAÇÃO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CONTAGEM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','COQUEIRAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CORAÇÃO DE JESUS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CORDISBURGO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CORDISLÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CORINTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','COROACI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','COROMANDEL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CORONEL FABRICIANO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CORONEL MURTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CORONEL PACHECO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CORONEL XAVIER CHAVES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','COUTO DE MAGALHAES DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CRISTAIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CRISTIANO OTONI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CRISTINA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CRISTÁLIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CRISÓLITA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CRUCILÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CRUZEIRO DA FORTALEZA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CRUZÍLIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CUPARAQUE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CURRAL DE DENTRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CURVELO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CÁSSIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CÔNEGO MARINHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CÓRREGO DANTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CÓRREGO DO BOM JESUS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CÓRREGO FUNDO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','CÓRREGO NOVO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DATAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DELFIM MOREIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DELFINÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DELTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DESCOBERTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DESTERRO DE ENTRE RIOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DESTERRO DO MELO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIAMANTINA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIOGO DE VASCONCELOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIONÍSIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIVINO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIVINO DAS LARANJEIRAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIVINOLÂNDIA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIVINÉSIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIVINÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIVISA ALEGRE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIVISA NOVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DIVISÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DOM BOSCO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DOM CAVATI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DOM JOAQUIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DOM SILVÉRIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DOM VIÇOSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DONA EUSÉBIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DORES DE CAMPOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DORES DE GUANHÃES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DORES DO INDAIÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DORES DO TURVO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DORESÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DOURADOQUARA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','DURANDÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ELÓI MENDES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ENGENHEIRO CALDAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ENGENHEIRO NAVARRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ENTRE FOLHAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ENTRE RIOS DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ERVÁLIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ESMERALDAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ESPERA FELIZ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ESPINOSA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ESPÍRITO SANTO DO DOURADO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ESTIVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ESTRELA DALVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ESTRELA DO INDAIÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ESTRELA DO SUL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','EUGENÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','EWBANK DA CÂMARA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','EXTREMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FAMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FARIA LEMOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FELISBURGO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FELIXLÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FELÍCIO DOS SANTOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FERNANDES TOURINHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FERROS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FERVEDOURO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FLORESTAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FORMIGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FORMOSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FORTALEZA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FORTUNA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FRANCISCO BADARÓ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FRANCISCO DUMONT')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FRANCISCO SÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FRANCISCÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FREI GASPAR')
SELECT 1 FROM DUAL;

INSERT ALL
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FREI INOCÊNCIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FREI LAGONEGRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FRONTEIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FRONTEIRA DOS VALES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FRUTA DE LEITE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FRUTAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','FUNILÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GALILÉIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GAMELEIRAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GLAUCILÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GOIABEIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GOIANÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GONZAGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GONÇALVES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GOUVEIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GOVERNADOR VALADARES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GRUPIARA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GRÃO MOGOL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUANHÃES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUAPÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUARACIABA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUARACIAMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUARANESIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUARANI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUARARÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUARDA-MOR')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUAXUPÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUIDOVAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUIMARÂNIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GUIRICEMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','GURINHATÃ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','HELIODORA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IAPU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IBERTIOGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IBIAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IBIRACATU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IBIRACI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IBIRITÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IBITIÚRA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IBITURUNA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IBIÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ICARAÍ DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IGARAPÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IGARATINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IGUATAMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IJACI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ILICÍNEA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IMBÉ DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','INCONFIDENTES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','INDAIABIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','INDIANÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','INGAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','INHAPIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','INHAÚMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','INIMUTABA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IPABA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IPANEMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IPATINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IPIAÇU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IPUIÚNA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','IRAÍ DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITABIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITABIRINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITABIRITO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITACAMBIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITACARAMBI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAGUARA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAIPÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAJUBÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAMARANDIBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAMARATI DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAMBACURI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAMBÉ DO MATO DENTRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAMOGI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAMONTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITANHANDU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITANHOMI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAOBIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAPAGIPE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAPECERICA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAPEVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITATIAIUÇU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAVERAVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAÚ DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITAÚNA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITUETA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITUIUTABA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITUMIRIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITURAMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ITUTINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JABOTICATUBAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JACINTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JACUTINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JACUÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JAGUARAÇU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JAMPRUCA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JANAÚBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JANUÁRIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JAPARAÍBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JAPONVAR')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JAÍBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JECEABA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JENIPAPO DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JEQUERI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JEQUITAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JEQUITIBÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JEQUITINHONHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JESUÂNIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JOANÉSIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JOAQUIM FELÍCIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JOAÍMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JORDÂNIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JOSENÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JOSÉ GONÇALVES DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JOSÉ RAYDAN')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JOÃO MONLEVADE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JOÃO PINHEIRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JUATUBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JUIZ DE FORA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JURAMENTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JURUAIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','JUVENÍLIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LADAINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAGAMAR')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAGOA DA PRATA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAGOA DOS PATOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAGOA DOURADA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAGOA FORMOSA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAGOA GRANDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAGOA SANTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAJINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAMBARI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAMIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LARANJAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LASSANCE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LAVRAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LEANDRO FERREIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LEME DO PRADO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LEOPOLDINA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LIBERDADE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LIMA DUARTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LIMEIRA DO OESTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LONTRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LUISBURGO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LUISLÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LUMINÁRIAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','LUZ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MACHACALIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MACHADO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MADRE DE DEUS DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MALACACHETA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MAMONAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MANGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MANHUAÇU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MANHUMIRIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MANTENA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MAR DE ESPANHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MARAVILHAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MARIA DA FÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MARIANA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MARILAC')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MARIPÁ DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MARLIÉRIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MARMELÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MARTINHO CAMPOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MARTINS SOARES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MATA VERDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MATERLÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MATEUS LEME')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MATHIAS LOBATO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MATIAS BARBOSA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MATIAS CARDOSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MATIPÓ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MATO VERDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MATOZINHOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MATUTINA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MEDEIROS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MEDINA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MENDES PIMENTEL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MERCÊS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MESQUITA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MINAS NOVAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MINDURI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MIRABELA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MIRADOURO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MIRAVÂNIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MIRAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MOEDA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MOEMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONJOLOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONSENHOR PAULO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONTALVÂNIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONTE ALEGRE DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONTE AZUL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONTE BELO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONTE CARMELO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONTE FORMOSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONTE SANTO DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONTE SIÃO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONTES CLAROS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MONTEZUMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MORADA NOVA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MORRO DA GARÇA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MORRO DO PILAR')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MUNHOZ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MURIAÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MUTUM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MUZAMBINHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','MÁRIO CAMPOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NACIP RAYDAN')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NANUQUE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NAQUE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NATALÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NATÉRCIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NAZARENO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NEPOMUCENO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NINHEIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVA BELÉM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVA ERA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVA LIMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVA MÓDICA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVA PONTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVA PORTEIRINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVA RESENDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVA SERRANA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVA UNIÃO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVO CRUZEIRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVO ORIENTE DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','NOVORIZONTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','OLARIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','OLHOS-D ÁGUA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','OLIVEIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','OLIVEIRA FORTES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','OLÍMPIO NORONHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ONÇA DE PITANGUI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ORATÓRIOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ORIZÂNIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','OURO BRANCO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','OURO FINO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','OURO PRETO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','OURO VERDE DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PADRE CARVALHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PADRE PARAÍSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PAI PEDRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PAINEIRAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PAINS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PAIVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PALMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PALMÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PAPAGAIOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PARACATU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PARAGUAÇU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PARAISÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PARAOPEBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PARÁ DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PASSA QUATRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PASSA TEMPO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PASSABÉM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PASSA-VINTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PASSOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PATIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PATOS DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PATROCÍNIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PATROCÍNIO DO MURIAÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PAULA CÂNDIDO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PAULISTAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PAVÃO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEDRA AZUL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEDRA BONITA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEDRA DO ANTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEDRA DO INDAIÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEDRA DOURADA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEDRALVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEDRAS DE MARIA DA CRUZ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEDRINÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEDRO LEOPOLDO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEDRO TEIXEIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEQUERI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEQUI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PERDIGÃO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PERDIZES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PERDÕES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PERIQUITO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PESCADOR')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PEÇANHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIAU')
SELECT 1 FROM DUAL;

INSERT ALL
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIEDADE DE CARATINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIEDADE DE PONTE NOVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIEDADE DO RIO GRANDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIEDADE DOS GERAIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIMENTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PINGO-D ÁGUA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PINTÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIRACEMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIRAJUBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIRANGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIRANGUINHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIRANGUÇU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIRAPETINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIRAPORA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIRAÚBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PITANGUI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PIUMHI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PLANURA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','POCRANE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','POMPÉU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PONTE NOVA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PONTO CHIQUE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PONTO DOS VOLANTES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PORTEIRINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PORTO FIRME')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','POTÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','POUSO ALEGRE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','POUSO ALTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','POÇO FUNDO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','POÇOS DE CALDAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PRADOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PRATA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PRATINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PRATÁPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PRESIDENTE BERNARDES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PRESIDENTE JUSCELINO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PRESIDENTE KUBITSCHEK')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PRESIDENTE OLEGÁRIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','PRUDENTE DE MORAIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','QUARTEL GERAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','QUELUZITO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RAPOSOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RAUL SOARES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RECREIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','REDUTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RESENDE COSTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RESPLENDOR')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RESSAQUINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIACHINHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIACHO DOS MACHADOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIBEIRÃO DAS NEVES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIBEIRÃO VERMELHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO ACIMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO CASCA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO DO PRADO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO DOCE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO ESPERA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO MANSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO NOVO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO PARANAÍBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO PARDO DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO PIRACICABA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO POMBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO PRETO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RIO VERMELHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RITÁPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ROCHEDO DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RODEIRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ROMARIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','ROSÁRIO DA LIMEIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RUBELITA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','RUBIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SABARÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SABINÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SACRAMENTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SALINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SALTO DA DIVISA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA BÁRBARA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA BÁRBARA DO LESTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA BÁRBARA DO MONTE VERDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA BÁRBARA DO TUGÚRIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA CRUZ DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA CRUZ DE SALINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA CRUZ DO ESCALVADO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA EFIGÊNIA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA FÉ DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA HELENA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA JULIANA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA LUZIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA MARGARIDA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA MARIA DE ITABIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA MARIA DO SALTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA MARIA DO SUAÇUÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA RITA DE CALDAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA RITA DE IBITIPOCA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA RITA DE JACUTINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA RITA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA RITA DO ITUETO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA RITA DO SAPUCAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA ROSA DA SERRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTA VITÓRIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTANA DA VARGEM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTANA DE CATAGUASES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTANA DE PIRAPAMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTANA DO DESERTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTANA DO GARAMBÉU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTANA DO JACARÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTANA DO MANHUAÇU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTANA DO PARAÍSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTANA DO RIACHO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTANA DOS MONTES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTO ANTÔNIO DO AMPARO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTO ANTÔNIO DO AVENTUREIRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTO ANTÔNIO DO GRAMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTO ANTÔNIO DO ITAMBÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTO ANTÔNIO DO JACINTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTO ANTÔNIO DO MONTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTO ANTÔNIO DO RETIRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTO ANTÔNIO DO RIO ABAIXO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTO HIPÓLITO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SANTOS DUMONT')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SAPUCAÍ-MIRIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SARDOÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SARZEDO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SEM-PEIXE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SENADOR AMARAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SENADOR CORTES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SENADOR FIRMINO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SENADOR JOSÉ BENTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SENADOR MODESTINO GONÇALVES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SENHORA DE OLIVEIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SENHORA DO PORTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SENHORA DOS REMÉDIOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SERICITA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SERITINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SERRA AZUL DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SERRA DA SAUDADE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SERRA DO SALITRE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SERRA DOS AIMORÉS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SERRANIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SERRANOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SERRANÓPOLIS DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SERRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SETE LAGOAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SETUBINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SILVEIRÂNIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SILVIANÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SIMONÉSIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SIMÃO PEREIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SOBRÁLIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SOLEDADE DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO BENTO ABADE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO BRÁS DO SUAÇUÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO DOMINGOS DAS DORES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO DOMINGOS DO PRATA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO FRANCISCO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO FRANCISCO DE PAULA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO FRANCISCO DE SALES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO FRANCISCO DO GLÓRIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO FÉLIX DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO GERALDO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO GERALDO DA PIEDADE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO GERALDO DO BAIXIO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO GONÇALO DO ABAETÉ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO GONÇALO DO PARÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO GONÇALO DO RIO ABAIXO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO GONÇALO DO RIO PRETO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO GONÇALO DO SAPUCAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO GOTARDO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOAQUIM DE BICAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOSÉ DA BARRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOSÉ DA LAPA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOSÉ DA SAFIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOSÉ DA VARGINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOSÉ DO ALEGRE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOSÉ DO DIVINO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOSÉ DO GOIABAL')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOSÉ DO JACURI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOSÉ DO MANTIMENTO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO BATISTA DO GLÓRIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO DA LAGOA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO DA MATA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO DA PONTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO DAS MISSÕES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO DEL REI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO DO MANHUAÇU')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO DO MANTENINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO DO ORIENTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO DO PACUÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO DO PARAÍSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO EVANGELISTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO JOÃO NEPOMUCENO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO LOURENÇO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO MIGUEL DO ANTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO PEDRO DA UNIÃO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO PEDRO DO SUAÇUÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO PEDRO DOS FERROS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO ROMÃO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO ROQUE DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO SEBASTIÃO DA BELA VISTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO SEBASTIÃO DA VARGEM ALEGRE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO SEBASTIÃO DO ANTA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO SEBASTIÃO DO MARANHÃO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO SEBASTIÃO DO OESTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO SEBASTIÃO DO PARAÍSO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO SEBASTIÃO DO RIO PRETO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO SEBASTIÃO DO RIO VERDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO THOMÉ DAS LETRAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO TIAGO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO TOMÁS DE AQUINO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','SÃO VICENTE DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TABULEIRO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TAIOBEIRAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TAPARUBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TAPIRA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TAPIRAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TAQUARAÇU DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TARUMIRIM')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TEIXEIRAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TEÓFILO OTONI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TIMÓTEO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TIRADENTES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TIROS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TOCANTINS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TOCOS DO MOJI')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TOLEDO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TOMBOS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TRÊS CORAÇÕES')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TRÊS MARIAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TRÊS PONTAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TUMIRITINGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TUPACIGUARA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TURMALINA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','TURVOLÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','UBAPORANGA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','UBAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','UBERABA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','UBERLÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','UBÁ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','UMBURATIBA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','UNAÍ')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','UNIÃO DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','URUANA DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','URUCUIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','URUCÂNIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VARGEM ALEGRE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VARGEM BONITA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VARGEM GRANDE DO RIO PARDO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VARGINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VARJÃO DE MINAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VARZELÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VAZANTE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VERDELÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VEREDINHA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VERMELHO NOVO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VERÍSSIMO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VESPASIANO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VIEIRAS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VIRGEM DA LAPA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VIRGINÓPOLIS')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VIRGOLÂNDIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VIRGÍNIA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VISCONDE DO RIO BRANCO')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VIÇOSA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VOLTA GRANDE')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','VÁRZEA DA PALMA')
INTO MUNICIPIOS (ID, NOME_MUNICIPIO) VALUES ('','WENCESLAU BRAZ')
SELECT 1 FROM DUAL;
=========================================================================================================================================================================